__author__ = 'vimalpat'

url = ('https://www.gmail.com')
username = ('')
acc_pass = ('')
Email = ('Email')
next = ('next')
password = ('Passwd')
sign_in = ('signIn')
compose = ('z0')
compose_xpath = ("//div[@gh='cm']")
mail_form = (':ok')
Recipient = (':oj')
to = ('textarea')
mailto = ('hiring@coriolis.co.in')
subject = (':oa')
sub_input = ('input')
sub_txt = ('Assignment by vimal')
body = (':pb')
body_txt = ('Name: Vimal Patidar\n Contact No : 8951449455\n Link to github:https://github.com/Git-vimal/vimalcode \n Note: Use instructions file to run the code')
send_btn_class = ('iN')
send_btn_xpath = ("//td[@class='gU Up']//div[@role='button']")
send_msg_txt = ('Your message has been sent. View message')
send_msg = ('vh')
send_msg_link = ('link_vsm')
